config/routes.rb
Myaccount::Application.routes.draw do
  devise_for :users

  root :to => "home#index"
  get "home/index"

  resources :months

  resources :years

  resources :mydebts

  resources :mybills

  match '/showmybills', :controller => 'home', :action => 'showmybills'
  match '/showhome', :controller => 'home', :action => 'home'
  match '/change_payment/(:id)', :controller => 'home', :action => 'change_payment'

  resources :users

end

app/models/mybill.rb
class Mybill < ActiveRecord::Base
  attr_accessible :amount, :confirmation, :payment, :title, :user_id, :due_date

  belongs_to :user

end

app/controllers/mybills_controller.rb
class MybillsController < ApplicationController
  # GET /mybills
  # GET /mybills.json
  def index
    @mybills = Mybill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mybills }
    end
  end

  # GET /mybills/1
  # GET /mybills/1.json
  def show
    @mybill = Mybill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mybill }
    end
  end

  # GET /mybills/new
  # GET /mybills/new.json
  def new
    @mybill = Mybill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mybill }
    end
  end

  # GET /mybills/1/edit
  def edit
    @mybill = Mybill.find(params[:id])
  end

  # POST /mybills
  # POST /mybills.json
  def create
    @mybill = Mybill.new(params[:mybill].merge(:user_id => current_user.id))

    respond_to do |format|
      if @mybill.save
        format.html { redirect_to @mybill, notice: 'Mybill was successfully created.' }
        format.json { render json: @mybill, status: :created, location: @mybill }
      else
        format.html { render action: "new" }
        format.json { render json: @mybill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mybills/1
  # PUT /mybills/1.json
  def update
    @mybill = Mybill.find(params[:id])

    respond_to do |format|
      if @mybill.update_attributes(params[:mybill])
        format.html { redirect_to @mybill, notice: 'Mybill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mybill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mybills/1
  # DELETE /mybills/1.json
  def destroy
    @mybill = Mybill.find(params[:id])
    @mybill.destroy

    respond_to do |format|
      format.html { redirect_to mybills_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mybills_helper.rb
module MybillsHelper
end

app/views/mybills/_form.html.erb
<%= form_for(@mybill) do |f| %>
  <% if @mybill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mybill.errors.count, "error") %> prohibited this mybill from being saved:</h2>

      <ul>
      <% @mybill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :user_id %> <%= current_user.id %> <br />
  </div>
  <div class="field">
    <%= f.label :due_date %>:
    <%= f.text_field :due_date, :id => 'mybill_due_date'%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mybills/edit.html.erb
<h1>Editing mybill</h1>

<%= render 'form' %>

<%= link_to 'Show', @mybill %> |
<%= link_to 'Back', mybills_path %>

app/views/mybills/index.html.erb
<h1>Listing mybills</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Amount</th>
    <th>Payment</th>
    <th>User</th>
    <th>Confirmation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mybills.each do |mybill| %>
  <tr>
    <td><%= mybill.title %></td>
    <td><%= mybill.amount %></td>
    <td><%= mybill.payment %></td>
    <td><%= mybill.user_id %></td>
    <td><%= mybill.confirmation %></td>
    <td><%= link_to 'Show', mybill %></td>
    <td><%= link_to 'Edit', edit_mybill_path(mybill) %></td>
    <td><%= link_to 'Destroy', mybill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mybill', new_mybill_path %>

app/views/mybills/new.html.erb
<h1>New mybill</h1>

<%= render 'form' %>

<%= link_to 'Back', mybills_path %>

app/views/mybills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @mybill.title %>
</p>

<p>
  <b>Amount:</b>
  <%= @mybill.amount %>
</p>

<p>
  <b>Payment:</b>
  <%= @mybill.payment %>
</p>

<p>
  <b>User:</b>
  <%= @mybill.user_id %>
</p>

<p>
  <b>Confirmation:</b>
  <%= @mybill.confirmation %>
</p>


<%= link_to 'Edit', edit_mybill_path(@mybill) %> |
<%= link_to 'Back', mybills_path %>