config/routes.rb
Myaccount::Application.routes.draw do
  devise_for :users

  root :to => "home#index"
  get "home/index"

  resources :months

  resources :years

  resources :mydebts

  resources :mybills

  match '/showmybills', :controller => 'home', :action => 'showmybills'
  match '/showhome', :controller => 'home', :action => 'home'
  match '/change_payment/(:id)', :controller => 'home', :action => 'change_payment'

  resources :users

end

app/models/mydebt.rb
class Mydebt < ActiveRecord::Base
  attr_accessible :amount, :confirmation, :payment, :title, :user_id

  belongs_to :user
end

app/controllers/mydebts_controller.rb
class MydebtsController < ApplicationController
  # GET /mydebts
  # GET /mydebts.json
  def index
    @mydebts = Mydebt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mydebts }
    end
  end

  # GET /mydebts/1
  # GET /mydebts/1.json
  def show
    @mydebt = Mydebt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mydebt }
    end
  end

  # GET /mydebts/new
  # GET /mydebts/new.json
  def new
    @mydebt = Mydebt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mydebt }
    end
  end

  # GET /mydebts/1/edit
  def edit
    @mydebt = Mydebt.find(params[:id])
  end

  # POST /mydebts
  # POST /mydebts.json
  def create
    @mydebt = Mydebt.new(params[:mydebt])

    respond_to do |format|
      if @mydebt.save
        format.html { redirect_to @mydebt, notice: 'Mydebt was successfully created.' }
        format.json { render json: @mydebt, status: :created, location: @mydebt }
      else
        format.html { render action: "new" }
        format.json { render json: @mydebt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mydebts/1
  # PUT /mydebts/1.json
  def update
    @mydebt = Mydebt.find(params[:id])

    respond_to do |format|
      if @mydebt.update_attributes(params[:mydebt])
        format.html { redirect_to @mydebt, notice: 'Mydebt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mydebt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mydebts/1
  # DELETE /mydebts/1.json
  def destroy
    @mydebt = Mydebt.find(params[:id])
    @mydebt.destroy

    respond_to do |format|
      format.html { redirect_to mydebts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mydebts_helper.rb
module MydebtsHelper
end

app/views/mydebts/_form.html.erb
<%= form_for(@mydebt) do |f| %>
  <% if @mydebt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mydebt.errors.count, "error") %> prohibited this mydebt from being saved:</h2>

      <ul>
      <% @mydebt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :payment %><br />
    <%= f.number_field :payment %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :confirmation %><br />
    <%= f.text_field :confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mydebts/edit.html.erb
<h1>Editing mydebt</h1>

<%= render 'form' %>

<%= link_to 'Show', @mydebt %> |
<%= link_to 'Back', mydebts_path %>

app/views/mydebts/index.html.erb
<h1>Listing mydebts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Amount</th>
    <th>Payment</th>
    <th>User</th>
    <th>Confirmation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mydebts.each do |mydebt| %>
  <tr>
    <td><%= mydebt.title %></td>
    <td><%= mydebt.amount %></td>
    <td><%= mydebt.payment %></td>
    <td><%= mydebt.user_id %></td>
    <td><%= mydebt.confirmation %></td>
    <td><%= link_to 'Show', mydebt %></td>
    <td><%= link_to 'Edit', edit_mydebt_path(mydebt) %></td>
    <td><%= link_to 'Destroy', mydebt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mydebt', new_mydebt_path %>

app/views/mydebts/new.html.erb
<h1>New mydebt</h1>

<%= render 'form' %>

<%= link_to 'Back', mydebts_path %>

app/views/mydebts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @mydebt.title %>
</p>

<p>
  <b>Amount:</b>
  <%= @mydebt.amount %>
</p>

<p>
  <b>Payment:</b>
  <%= @mydebt.payment %>
</p>

<p>
  <b>User:</b>
  <%= @mydebt.user_id %>
</p>

<p>
  <b>Confirmation:</b>
  <%= @mydebt.confirmation %>
</p>


<%= link_to 'Edit', edit_mydebt_path(@mydebt) %> |
<%= link_to 'Back', mydebts_path %>