config/routes.rb
Myaccount::Application.routes.draw do
  devise_for :users

  root :to => "home#index"
  get "home/index"

  resources :months

  resources :years

  resources :mydebts

  resources :mybills

  match '/showmybills', :controller => 'home', :action => 'showmybills'
  match '/showhome', :controller => 'home', :action => 'home'
  match '/change_payment/(:id)', :controller => 'home', :action => 'change_payment'

  resources :users

end

app/models/year.rb
class Year < ActiveRecord::Base
  attr_accessible :user_id, :year_name
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  # GET /years
  # GET /years.json
  def index
    @years = Year.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @years }
    end
  end

  # GET /years/1
  # GET /years/1.json
  def show
    @year = Year.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @year }
    end
  end

  # GET /years/new
  # GET /years/new.json
  def new
    @year = Year.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @year }
    end
  end

  # GET /years/1/edit
  def edit
    @year = Year.find(params[:id])
  end

  # POST /years
  # POST /years.json
  def create
    @year = Year.new(params[:year])

    respond_to do |format|
      if @year.save
        format.html { redirect_to @year, notice: 'Year was successfully created.' }
        format.json { render json: @year, status: :created, location: @year }
      else
        format.html { render action: "new" }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /years/1
  # PUT /years/1.json
  def update
    @year = Year.find(params[:id])

    respond_to do |format|
      if @year.update_attributes(params[:year])
        format.html { redirect_to @year, notice: 'Year was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /years/1
  # DELETE /years/1.json
  def destroy
    @year = Year.find(params[:id])
    @year.destroy

    respond_to do |format|
      format.html { redirect_to years_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/_form.html.erb
<%= form_for(@year) do |f| %>
  <% if @year.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@year.errors.count, "error") %> prohibited this year from being saved:</h2>

      <ul>
      <% @year.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :mybill_id %><br />
    <%= f.number_field :mybill_id %>
  </div>
  <div class="field">
    <%= f.label :mydebt_id %><br />
    <%= f.number_field :mydebt_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/years/edit.html.erb
<h1>Editing year</h1>

<%= render 'form' %>

<%= link_to 'Show', @year %> |
<%= link_to 'Back', years_path %>

app/views/years/index.html.erb
<h1>Listing years</h1>

<table>
  <tr>
    <th>Year</th>
    <th>User</th>
    <th>Mybill</th>
    <th>Mydebt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @years.each do |year| %>
  <tr>
    <td><%= year.year %></td>
    <td><%= year.user_id %></td>
    <td><%= year.mybill_id %></td>
    <td><%= year.mydebt_id %></td>
    <td><%= link_to 'Show', year %></td>
    <td><%= link_to 'Edit', edit_year_path(year) %></td>
    <td><%= link_to 'Destroy', year, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Year', new_year_path %>

app/views/years/new.html.erb
<h1>New year</h1>

<%= render 'form' %>

<%= link_to 'Back', years_path %>

app/views/years/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Year:</b>
  <%= @year.year %>
</p>

<p>
  <b>User:</b>
  <%= @year.user_id %>
</p>

<p>
  <b>Mybill:</b>
  <%= @year.mybill_id %>
</p>

<p>
  <b>Mydebt:</b>
  <%= @year.mydebt_id %>
</p>


<%= link_to 'Edit', edit_year_path(@year) %> |
<%= link_to 'Back', years_path %>